data:
  start_date: "2012-01-01"
  end_date: "2024-12-31"
  tickers:
    - AAPL
    - MSFT
    - GOOGL
    - META
    - AMZN
    - NVDA
    - TSLA
    - ORCL
    - AVGO
    - AMD
    - INTC
  indexes:
    - ^GSPC
    - ^NDX
    - ^VIX

  features:
    window_size: 60
    pca_components: 3

  splits:
    train_end: "2018-12-31"
    val_end: "2021-12-31"
    test_end: "2024-12-31"